name: dementia_memory_app
description: "A new Flutter project."

# Prevents the package from being published accidentally.
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0  # Ensure this is the latest version
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  image_picker: ^1.1.2
  image: ^4.1.3
  path: ^1.9.1
  intl: ^0.20.2
  permission_handler: ^11.4.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.5.2
  natural_language: ^0.0.4
  dart_openai: ^5.1.0
  material_color_utilities: ^0.11.1
  syncfusion_flutter_charts: ^28.2.9  # Pie Chart
  google_ml_kit: ^0.19.0
  google_mlkit_smart_reply: ^0.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo1.jpg"
  adaptive_icon_foreground: "assets/logo1.jpg"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/logo1.jpg
